# Generated by Django 3.2.5 on 2021-09-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createappointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
