# Generated by Django 3.2.5 on 2021-09-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_createappointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createappointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
